export const MAX_MUSIC_NAME_SIZE_LARGE_SCREENS = 20

export const MAX_MUSIC_NAME_SIZE_MEDIUM_SCREENS = 14 

export const MAX_MUSIC_NAME_SIZE_SMALL_SCREENS = 12

export const SMALL_SCREEN_BP = 576

export const MEDIUM_SCREEN_BP = 768

export const LARGE_SCREEN_BP = 992